dist: trusty
sudo: required
group: edge

language:
  - python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install --no-install-recommends -y iperf3

install: "pip install requests"

script:
  - bash ./speed.sh
  - python ./speed.py
